export const filterConfig = [
  {
    id: "priceRange",
    label: "Price Range",
    type: "range",
    defaultOpen: true,
    min: 0,
    max: 100000,
    step: 10,
    defaultValue: [0, 100000],
    unit: "৳",
  },
  {
    id: "brand",
    label: "Brand",
    type: "checkbox",
    defaultOpen: true,
    options: [
      { value: "acer", label: "Acer" },
      { value: "asus", label: "ASUS" },
      { value: "benq", label: "BenQ" },
      { value: "dell", label: "Dell" },
      { value: "gigabyte", label: "Gigabyte" },
      { value: "lg", label: "LG" },
      { value: "msi", label: "MSI" },
      { value: "samsung", label: "Samsung" },
    ],
  },
  {
    id: "panelType",
    label: "Panel Type",
    type: "checkbox",
    defaultOpen: true,
    options: [
      { value: "ips", label: "IPS" },
      { value: "va", label: "VA" },
      { value: "oled", label: "OLED" },
      { value: "nano-ips", label: "Nano IPS" },
      { value: "mini-led", label: "Mini-LED" },
    ],
  },
  {
    id: "resolution",
    label: "Resolution",
    type: "checkbox",
    defaultOpen: false,
    options: [
      { value: "fhd", label: "FHD", hint: "1920×1080" },
      { value: "qhd", label: "QHD", hint: "2560×1440" },
      { value: "uwqhd", label: "UWQHD", hint: "3440×1440" },
      { value: "4k", label: "4K", hint: "3840×2160" },
      { value: "5k", label: "5K", hint: "5120×2880" },
    ],
  },
  {
    id: "refreshRate",
    label: "Refresh Rate",
    type: "checkbox",
    defaultOpen: false,
    options: [
      // { value: "60", label: "60Hz" },
      // { value: "75", label: "75Hz" },
      // { value: "120", label: "120Hz" },
      { value: "144", label: "144Hz" },
      // { value: "165", label: "165Hz" },
      { value: "180", label: "180Hz" },
      { value: "200", label: "200Hz" },
      // { value: "240", label: "240Hz+" },
    ],
  },
  {
    id: "useCase",
    label: "Use Case",
    type: "checkbox",
    defaultOpen: false,
    options: [
      { value: "gaming", label: "Gaming" },
      { value: "office", label: "Office" },
      { value: "professional", label: "Professional" },
      { value: "content-creation", label: "Content Creation" },
    ],
  },
  {
    id: "colorAccuracyTier",
    label: "Color Accuracy Tier",
    type: "checkbox",
    defaultOpen: false,
    options: [
      {
        value: "calman",
        label: "Calman Verified",
        logo: "/images/logo/calman.png",
      },
      {
        value: "spyder",
        label: "Spyder Verified",
        logo: "/images/logo/data-color.jpg",
      },
    ],
  },

  {
    id: "deltaE",
    label: "Delta E (Max)",
    type: "range",
    defaultOpen: false,
    min: 0,
    max: 5,
    step: 0.1,
    defaultValue: 5,
    unit: "≤",
    hint: "< 1 Excellent · < 2 Good · < 3 Acceptable",
  },
  {
    id: "srgb",
    label: "sRGB Coverage (Min %)",
    type: "range",
    defaultOpen: false,
    min: 80,
    max: 100,
    step: 1,
    defaultValue: 80,
    unit: "≥",
  },
  {
    id: "dciP3",
    label: "DCI-P3 Coverage (Min %)",
    type: "range",
    defaultOpen: false,
    min: 70,
    max: 100,
    step: 1,
    defaultValue: 70,
    unit: "≥",
  },
];
